version: '3.8'

services:
  server:
    build:
      context: .
      target: server
    ports:
      - "5050:5050"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PORT=5050
      - WEB_ORIGIN=http://localhost:3000
    restart: unless-stopped

  web:
    build:
      context: .
      target: web
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SERVER_URL=http://server:5050
    depends_on:
      - server
    restart: unless-stopped